#ifndef _VRTIMERS_H_
#define _VRTIMERS_H_

#include "hal.h"

#define VR1_TIM TIM15
#define VR2_TIM TIM16
#define VR3_TIM TIM17

#define VR1_OVERFLOW_HANDLER TIM15_OVERFLOW_HANDLER
#define VR2_OVERFLOW_HANDLER TIM16_OVERFLOW_HANDLER
#define VR3_OVERFLOW_HANDLER TIM17_OVERFLOW_HANDLER

#define VR1_COMPARE_HANDLER TIM15_COMPARE_HANDLER
#define VR2_COMPARE_HANDLER TIM16_COMPARE_HANDLER
#define VR3_COMPARE_HANDLER TIM17_COMPARE_HANDLER

void setupTimers(void);


#endif
